apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: kube-cluster
  name: "clusterapi:controller-manager"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "clusterapi:controller-manager"
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: default
  namespace: kube-cluster
# TODO: create specific service account
