apiVersion: v1
kind: Service
metadata:
  name: clusterapi
  namespace: kube-cluster
  labels:
    api: clusterapi
    apiserver: "true"
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 6443
  selector:
    api: clusterapi
    apiserver: "true"
