apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clusterapi
  namespace: kube-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: kube-cluster
# TODO: create specifics service accounts
