apiVersion: "cluster.k8s.io/v1alpha1"
kind: Cluster
metadata:
  name: test
  namespace: test
spec:
  clusterNetwork:
    services:
      cidrBlocks:
        - "10.0.0.1/24"
    pods:
      cidrBlocks:
        - "10.0.0.2/24"
    serviceDomain: example.com
  providerConfig:
    value:
      apiVersion: awsproviderconfig/v1alpha1
      kind: AWSClusterProviderConfig
      clusterId: meh.tectonic.kuwit.rocks
      clusterVersionRef:
        namespace: test
        name: test
      hardware:
        aws:
#          accountSecret:
#            name: test-aws-creds
          sshSecret:
            name: tectonic
          sshUser: centos
          sslSecret:
            name: test-certs
          region: eu-west-1
          keyPairName: tectonic
      defaultHardwareSpec:
        aws:
          instanceType: m4.large
      machineSets:
        - nodeType: Master
          size: 1
        - shortName: infra
          nodeType: Compute
          infra: true
          size: 1
        - shortName: compute
          nodeType: Compute
          size: 1
