---
apiVersion: cluster.k8s.io/v1alpha1
kind: Cluster
metadata:
  name: test
  namespace: test
spec:
  clusterNetwork:
    services:
      cidrBlocks:
        - "10.0.0.1/24"
    pods:
      cidrBlocks:
        - "10.0.0.2/24"
    serviceDomain: example.com
  providerConfig:
    value:
      apiVersion: awsproviderconfig/v1alpha1
      kind: AWSClusterProviderConfig
      region: "{{ .ClusterConfig.Region }}"
      keyPairName: "{{ .ClusterConfig.KeyPairName }}"
      vpcName: "{{ .ClusterConfig.VPCName }}"
