apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: machinehealthchecks.healthchecking.openshift.io
spec:
  group: healthchecking.openshift.io
  names:
    kind: MachineHealthCheck
    plural: machinehealthchecks
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Specification of machine health check policy
          properties:
            selector:
              description: Label selector to match machines whose health will be exercised
              type: object
          required:
          - selector
          type: object
        status:
          description: Most recently observed status of MachineHealthCheck resource
          properties:
            targetedConditions:
              items:
                properties:
                  name:
                    type: string
                  status:
                    type: string
                required:
                - name
                - status
                type: object
              type: array
            targetedMachines:
              items:
                properties:
                  healthy:
                    type: string
                  name:
                    type: string
                  unhealthyConditions:
                    items:
                      type: string
                    type: array
                required:
                - name
                - healthy
                - unhealthyConditions
                type: object
              type: array
            totalHealthyMachines:
              format: int32
              type: integer
          required:
          - targetedMachines
          - targetedConditions
          - totalHealthyMachines
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
