---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: machine-api-operator
  namespace: openshift-cluster-api
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: https
    scheme: https
    tlsConfig:
      # TODO where do you mount the service-ca.crt?
      insecureSkipVerify: true
      serverName: metrics.machine-api-operator.svc
  jobLabel: component
  namespaceSelector:
    matchNames:
    - openshift-cluster-api
  selector:
    matchLabels:
      k8s-app: machine-api-operator
